#!/bin/bash

domain=$1
subdomain=$2

# Function to display information about a subdomain
function display_info {
  record_type=$(dig $1.$2 +short | awk -F '.' '{print $2}')
  destination=$(dig $1.$2 +short)
  echo "The subdomain $1 is a $record_type record and points to $destination"
}

if [ -z "$subdomain" ]; then
  # Display information for default subdomains
  display_info www $domain
  display_info lb-01 $domain
  display_info web-01 $domain
  display_info web-02 $domain
else
  # Display information for specified subdomain
  display_info $subdomain $domain
fi
